spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.sql.init.mode=never
blueprints.security.issuer=https://decsis-eci/blueprints
blueprints.security.token-ttl-seconds=3600
